### ISSUE TITLE
IdentityServer on WebFarm

### ISSUE THREAD

**Issue by sennaapp** [IdentityServer/Thinktecture.IdentityServer3#1029]
I have installed IdentityServer on web farm ( 2 Azure vm in a load balanced cloud service). I have javascipt client using implicit flow in authentication. Login works 50% of the times but on other times it displays "Unexpected error". From log files I can find following exception (below). I believe this is the cause. Problem doesn't occur if I shut down other machine from farm, so it is related to the situation where requests go to separate machines. 

What should I do to solve this? Is setting same static <machineKey> for both machines sufficient solution f.ex. ?

I have also tried to install IdentityManager to this same farm (on both machines) and it should authenticate using IdentityServer. Login and logout behave weirdly (everything is working locally). Is it possible to make it work on this kind of setup?

Message: AntiForgeryTokenValidator validating token
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at Microsoft.Owin.Security.DataProtection.AppBuilderExtensions.CallDataProtectionProvider.CallDataProtection.Unprotect(Byte[] protectedData) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\InMemoryFactory.cs:line 0
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AntiForgeryToken.<GetHiddenInputTokenAsync>d__7.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\AntiForgeryToken.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AntiForgeryToken.<IsTokenValid>d__1.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\AntiForgeryToken.cs:line 68

**Comment by sennaapp** [comment]
And I'm using IdentityServer v3 1.0 and latest beta version of identityManager

**Comment by loctanvo** [comment]
The antiforgerytoken is created and validated using the Owin DataProtector. In IdServer, if you don't specify the data protector, it'll try to resolve the IDataProtectionProvider and retrieve a data protector. If you are using Microsoft.Owin.Host.SystemWeb for hosting in IIS, the MachineKey data protector is configured as default. If you don't, and no IDataProtectorProvider configured in Owin, IdServer will use the DpapiDataProtector. This one can be coupled to the user running the process, so you should have that in mind when protecting/unprotecting your data.

If you are using the MachineKey data protector (by using Microsoft.Owin.Host.SystemWeb), you'll have a problem when one web server protects and another one unprotects, unless you specify a machine key for your app. If you do that, you'll be fine.

We are using the X509CertificateDataProtector to solve the same issue.

**Comment by leastprivilege** [comment]
IOW - in IIS you need to sync the machine keys. Outside of IIS you need to use the X509CertificateDataProtector.

**Comment by firasr** [comment]
This may sounds straightforward question, but how to tell if the application runs inside/outside IIS?
