### ISSUE TITLE
“An exception of type 'System.Security.Cryptography.CryptographicException' occurred in System.Security.dll but was not handled in user code”

### ISSUE THREAD

**Issue by sania13** [IdentityServer/Thinktecture.IdentityServer3#935]
It worked fine for me before, but when I get the latest sample code I started to receive this errors:

“An exception of type 'System.Security.Cryptography.CryptographicException' occurred in System.Security.dll but was not handled in user code”
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at System.Security.Cryptography.DpapiDataProtector.ProviderUnprotect(Byte[] encryptedData)
   at System.Security.Cryptography.DataProtector.Unprotect(Byte[] encryptedData)
   at Microsoft.Owin.Security.DataProtection.DpapiDataProtector.Unprotect(Byte[] protectedData) in c:\projects\thinktecture\source\Core\Services\Default\DefaultTokenService.cs:line 0
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.HostDataProtector.Unprotect(Byte[] data, String entropy) in c:\projects\thinktecture\source\Core\Configuration\Hosting\HostDataProtector.cs:line 39
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.DataProtectorAdapter.Unprotect(Byte[] protectedData) in c:\projects\thinktecture\source\Core\Configuration\Hosting\DataProtectorAdapter.cs:line 37
   at Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Unprotect(String protectedText) in c:\projects\thinktecture\source\Core\Services\Default\DefaultTokenService.cs:line 0

Message: “The parameter is incorrect.”

Same error for different Identity Server configurations.

**Comment by brockallen** [comment]
My first reaction is that you don't have a consistent `<machineKey>`. But I still don't feel like there's enough info to really go on. Can you explain the steps to reproduce.

**Comment by johnkors** [comment]
We actually stumpled upon this issue running in Azure as well. I guess the machinekey varies when MS decicdes to put our idsrv on a different instance.

**Comment by sania13** [comment]
I did not make any configuration changes.

1)	Downloaded sample code.
2)	Run AspNetIdentity (same for WebHost(minimal), MembershipRebot) project as Identity Server
3)	Run MVC OWIN Client (same for other clients too)
4)	Click on “Claims’ menu item and get error.

It works fine for the samples that I downloaded on 1/26/2015.

Please note in the error message that path “c:\projects\thinktecture\source\Core\Services\Default\DefaultTokenService.cs” is not my local path..

**Comment by brockallen** [comment]
I just did the exact same and it works for me. I wonder if you have a persistent cookie from an earlier run -- see if you have any leftover cookies.

**Comment by sania13** [comment]
I cleaned the cookies and removed IISExpress configuration and it did fix some problems. It does work with some Identity Servers (CustomViewService, CustomUserService), but AspNetIdentity still does not work and produces the same error. 

The ‘WebHost (minimal)’ server points to “https://localhost:44333”, but all others servers start with “https://localhost:44333/core”. Any reason why it is different?

**Comment by brockallen** [comment]
Just different samples got configured differently. All of them ultimately have IdSvr on https://localhost:44333/core

**Comment by brockallen** [comment]
Can we close this?

**Comment by sania13** [comment]
Yes. Thank you.
