### ISSUE TITLE
Cryptographic Exception on HostDataProtector provider

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/Thinktecture.IdentityServer3#992]
I'm stuck on this one. When my IdSvr3 project gets called for an OAuth request the IdSvr3 project throws a Cryptographic Exception.  I have the source in my project and it was throwing the exception from the HostDataProtector.cs, in the Unprotect method when it calls Unprotect on the protector.

I downloaded the source for the IdentityManager and updated its nuget to use the updated IdSvr3 binary and it also does the same thing. I tried version 1.1.1 and 1.1.0.  Any ideas?  It could be my computer, I have no idea...

Exception data:
System.Security.Cryptography.CryptographicException was unhandled by user code
  HResult=-2146233296
  Message=Error occurred during a cryptographic operation.
  Source=System.Web
  StackTrace:
       at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
       at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.Unprotect(Byte[] protectedData)
       at System.Web.Security.MachineKey.Unprotect(ICryptoServiceProvider cryptoServiceProvider, Byte[] protectedData, String[] purposes)
       at System.Web.Security.MachineKey.Unprotect(Byte[] protectedData, String[] purposes)
       at Microsoft.Owin.Host.SystemWeb.DataProtection.MachineKeyDataProtector.Unprotect(Byte[] protectedData)
       at Microsoft.Owin.Security.DataProtection.AppBuilderExtensions.CallDataProtectionProvider.CallDataProtection.Unprotect(Byte[] protectedData) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\Default\DefaultTokenService.cs:line 0
       at Thinktecture.IdentityServer.Core.Configuration.Hosting.HostDataProtector.Unprotect(Byte[] data, String entropy) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\HostDataProtector.cs:line 39
       at Thinktecture.IdentityServer.Core.Configuration.Hosting.DataProtectorAdapter.Unprotect(Byte[] protectedData) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\DataProtectorAdapter.cs:line 37
       at Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Unprotect(String protectedText) in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\Default\DefaultTokenService.cs:line 0
  InnerException:

**Comment by gilm0079** [comment]
Update: This exception only happens when running the projects with non-SSL communication.  I switched them over to use SSL and there are no exceptions.

**Comment by gilm0079** [comment]
n/m, I lied. It continues to happen when using SSL as well.  In the trace logs I see a "Redirecting to login page" event followed by a Protecting message: {"ReturnUrl":"https://localhost:44305/ids/connect/authorize?state=48160713125253815&client_id=idmgr&redirect_uri=https%3A%2F%2Flocalhost%3A44305%2Fidm%2F%23%2Fcallback%2F&response_type=token&scope=idmgr","ClientId":"idmgr","AcrValues":[],"Created":635605723489455740}
After that the cryptographicException is thrown.

**Comment by leastprivilege** [comment]
How are you hosting? Clear all cookies in your browser.

Search for closed issues.

**Comment by gilm0079** [comment]
Debugging in VS2013 using chrome browser and IIS Express.  

I just cleared my cookies and it didn't throw the exception.  I then tried to reproduce the error: logging in, logging out, restarting VS debug when logged out, restarting VS debug when logged in.  No luck reproducing it.  

Could it be a bad local cookie (correct cookie name with bad contents)?  Do you think it would be worth while to have the hosting app burn the client browser cookie if a cryptographic exception is thrown and reload the page?  I think the only way I've seen to destroy client side cookies, at least from the server, is to create a new cookie with an expired date and send that to the client.  The browser will then dispose of the cookie.

**Comment by leastprivilege** [comment]
We have a number of counter measures - still this can happen - e.g. when for some reason the machine key has changed.
